# Generated by Django 5.2.4 on 2025-07-05 23:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContextEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The raw content of the context entry.')),
                ('source_type', models.CharField(choices=[('whatsapp', 'WhatsApp Message'), ('email', 'Email'), ('note', 'Note'), ('other', 'Other')], default='note', help_text='The type of the context source (e.g., WhatsApp, Email, Note).', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='The original timestamp of the context entry.')),
                ('processed_insights', models.JSONField(blank=True, help_text='JSON field to store AI-processed insights (e.g., keywords, sentiment, entities).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the entry was created in the system.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the entry was last updated.')),
            ],
            options={
                'verbose_name': 'Context Entry',
                'verbose_name_plural': 'Context Entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
