# Generated by Django 5.2.4 on 2025-07-05 23:03

import django.db.models.deletion
import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the category.', max_length=100, unique=True)),
                ('usage_frequency', models.IntegerField(default=0, help_text='How often this category is used.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the category was created.')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the task.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='A detailed description of the task.', null=True)),
                ('priority_score', models.DecimalField(decimal_places=2, default=0.0, help_text='AI-generated priority score for the task (e.g., 0.00 to 100.00).', max_digits=5)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Human-readable priority level (Low, Medium, High, Urgent).', max_length=10)),
                ('deadline', models.DateTimeField(blank=True, default=tasks.models.default_deadline, help_text='The suggested or set deadline for the task.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='pending', help_text='The current status of the task.', max_length=20)),
                ('is_ai_suggested', models.BooleanField(default=False, help_text='Indicates if this task was suggested by the AI.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the task was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the task was last updated.')),
                ('category', models.ForeignKey(blank=True, help_text='The category or tag associated with the task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.category')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-priority_score', 'deadline', 'created_at'],
            },
        ),
    ]
